CREATE PROCEDURE ADD_CONFERENCE(
  conf_name IN CONFERENCES.CONFERENCE_NAME%TYPE,
  country IN CONFERENCES.COUNTRY%TYPE,
  city IN CONFERENCES.CITY%TYPE,
  address IN CONFERENCES.ADDRESS%TYPE,
  first_day IN CONFERENCES.FIRST_DAY%TYPE,
  last_day IN CONFERENCES.LAST_DAY%TYPE,
  student_discount IN CONFERENCES.STUDENT_DISCOUNT%TYPE DEFAULT 0
) AS
BEGIN
  INSERT INTO CONFERENCES(CONFERENCE_NAME, COUNTRY, CITY, ADDRESS, FIRST_DAY, LAST_DAY, STUDENT_DISCOUNT)
    VALUES(conf_name, country, city, address, first_day, last_day, student_discount);
END;


CREATE PROCEDURE ADD_CONFERENCE_DAY(
  conf_id IN CONFERENCE_DAYS.CONFERENCE_ID%TYPE,
  price IN CONFERENCE_DAYS.PRICE%TYPE,
  limit IN CONFERENCE_DAYS.LIMIT%TYPE,
  day_date IN CONFERENCE_DAYS.DAY_DATE%TYPE
) AS
BEGIN
  INSERT INTO CONFERENCE_DAYS(CONFERENCE_ID, PRICE, LIMIT, DAY_DATE)
    VALUES(conf_id, price, limit, day_date);
END;


CREATE PROCEDURE ADD_WORKSHOPS(
  conf_day_id IN WORKSHOPS.CONF_DAY_ID%TYPE,
  start_time IN WORKSHOPS.START_TIME%TYPE,
  end_time IN WORKSHOPS.END_TIME%TYPE,
  price IN WORKSHOPS.PRICE%TYPE,
  limit IN WORKSHOPS.LIMIT%TYPE
) AS
BEGIN
  INSERT INTO WORKSHOPS(CONF_DAY_ID, START_TIME, END_TIME, PRICE, LIMIT)
    VALUES(conf_day_id, start_time, end_time, price, limit);
END;


CREATE PROCEDURE ADD_PRICE(
  conf_id IN PRICES.CONFERENCE_ID%TYPE,
  discount IN PRICES.DISCOUNT%TYPE,
  end_date IN PRICES.END_DATE%TYPE
) AS
BEGIN
  INSERT INTO PRICES(CONFERENCE_ID, DISCOUNT, END_DATE)
    VALUES(conf_id, discount, end_date);
END;

-- CREATE PACKAGE ...? AS ...!