// Najczęsci klienci//
CREATE VIEW The_Best_Clients_V AS
SELECT CLIENT_NAME,COUNT(*) AS "the number of transactions"
FROM BOOKINGS
       JOIN CLIENTS ON BOOKINGS.CLIENT_ID = CLIENTS.CLIENT_ID
GROUP BY BOOKINGs.CLIENT_ID, CLIENT_NAME
ORDER BY COUNT(*) DESC


//Klienci którzy zalegają z wpłatą//
CREATE VIEW People_Default_With_Payment AS
SELECT CLIENT_NAME
FROM BOOKINGS
            JOIN CLIENTS ON BOOKINGS.CLIENT_ID = CLIENTS.CLIENT_ID
WHERE BOOKING_ID NOT IN (SELECT BOOKING_ID FROM PAYMENTS);


//Dostepne konferencje//
CREATE VIEW Available_Conferences_V AS
SELECT DISTINCT CONFERENCE_NAME
FROM CONFERENCES
       JOIN CONFERENCE_DAYS ON CONFERENCES.CONFERENCE_ID = CONFERENCE_DAYS.CONFERENCE_ID
       JOIN CONF_DAY_BOOKINGS ON CONF_DAY_BOOKINGS.CONF_DAY_ID = CONFERENCE_DAYS.CONF_DAY_ID
GROUP BY CONF_DAY_BOOKINGS.CONF_DAY_ID, CONFERENCE_NAME
HAVING LIMIT > SUM(NUMBER_OF_ATTENDEES)


//Dostepne dni konferencji//
CREATE VIEW Available_Conference_Days_V AS
SELECT CONFERENCE_NAME, DAY_DATE
FROM CONFERENCE_DAYS
       JOIN CONFERENCES ON CONFERENCE_DAYS.CONFERENCE_ID = CONFERENCES.CONFERENCE_ID
       JOIN CONF_DAY_BOOKINGS ON CONFERENCE_DAYS.CONF_DAY_ID = CONF_DAY_BOOKINGS.CONF_DAY_ID
GROUP BY  CONF_DAY_BOOKINGS.CONF_DAY_ID, CONFERENCE_NAME, DAY_DATE, LIMIT
HAVING LIMIT > SUM(NUMBER_OF_ATTENDEES)


//Dostępne warsztaty//
CREATE VIEW Available_Workshops_V AS
SELECT CONFERENCE_NAME, DAY_DATE, WORKSHOP_BOOKINGS.WORKSHOP_ID
FROM WORKSHOPS
       JOIN WORKSHOP_BOOKINGS ON WORKSHOPS.WORKSHOP_ID = WORKSHOP_BOOKINGS.WORKSHOP_ID
       JOIN CONFERENCE_DAYS ON WORKSHOPS.CONF_DAY_ID = CONFERENCE_DAYS.CONF_DAY_ID
       JOIN CONFERENCES ON CONFERENCES.CONFERENCE_ID = CONFERENCE_DAYS.CONFERENCE_ID
GROUP BY WORKSHOP_BOOKINGS.WORKSHOP_ID, CONFERENCE_NAME, DAY_DATE, WORKSHOPS.LIMIT
HAVING WORKSHOPS.LIMIT > SUM(NUMBER_OF_ATTENDEES)

//Lista obecnosci na przyszlych dniach konferencji//
CREATE VIEW Participation_Conference_Days_V AS
SELECT FIRST_NAME, LAST_NAME, CONFERENCE_NAME, DAY_DATE
FROM PARTICIPATION_CONF_DAYS
       JOIN ATTENDEES on PARTICIPATION_CONF_DAYS.ATTENDEE_ID = ATTENDEES.ATTENDEE_ID
       JOIN CONFERENCE_DAYS on PARTICIPATION_CONF_DAYS.CONF_DAY_ID = CONFERENCE_DAYS.CONF_DAY_ID
       JOIN CONFERENCES on CONFERENCE_DAYS.CONFERENCE_ID = CONFERENCES.CONFERENCE_ID
       where DAY_DATE > CURRENT_DATE

//Lista obecności na przyszlym warsztacie//
CREATE VIEW Participation_Workshop_V AS
SELECT FIRST_NAME, LAST_NAME, CONFERENCE_NAME, DAY_DATE, WORKSHOP_ID
FROM PARTICIPATION_WORKSHOPS
       JOIN PARTICIPATION_CONF_DAYS
            ON PARTICIPATION_CONF_DAYS.PARTICIPATION_CONF_DAY_ID = PARTICIPATION_WORKSHOPS.PARTICIPATION_CONF_DAY_ID
       JOIN ATTENDEES ON PARTICIPATION_CONF_DAYS.ATTENDEE_ID = ATTENDEES.ATTENDEE_ID
       JOIN CONFERENCE_DAYS ON PARTICIPATION_CONF_DAYS.CONF_DAY_ID = CONFERENCE_DAYS.CONF_DAY_ID
       JOIN CONFERENCES ON CONFERENCE_DAYS.CONFERENCE_ID = CONFERENCES.CONFERENCE_ID
       WHERE DAY_DATE > CURRENT_DATE

            
            
