DROP TABLE PARTICIPATION_WORKSHOPS;
DROP TABLE WORKSHOP_BOOKINGS;
DROP TABLE WORKSHOPS;
DROP TABLE CONF_DAY_BOOKINGS;
DROP TABLE PARTICIPATION_CONF_DAYS;
DROP TABLE CONFERENCE_DAYS;
DROP TABLE PRICES;
DROP TABLE PAYMENTS;
DROP TABLE BOOKINGS;
DROP TABLE CONFERENCES;
DROP TABLE CLIENTS;
DROP TABLE ATTENDEES;

PURGE RECYCLEBIN;